# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Hello, I'm a bot! I have a few things I want to share that can make your issue a lot simpler to understand. ðŸ˜Š

  Important for DRM-free copies! If you game does not have voices, there's a big chance you are running an old version of the game, **and that means it is incompatible with our patch.** Check inside your ``StreamingAssets`` folder if you have a ``CompiledUpdateScripts`` folder. If it's not there... then go in the MangaGamer store and download the game again. Steam users don't have to worry about this!

  1. Did you remember to properly describe what is happening (or what you found)? Giving some clues such as where it happens (like a line of dialog exactly like the one displayed in the game) helps a lot!

  2. If you are having issues **installing** the patch, did you notice anything strange? Any errors in the command line window that appears while installing the patch?

  3. Please post your computer specs! Knowing if you are running Windows, Mac or Linux helps a lot when answering to issues. If you don't know how to find your computer specs, running ``dxdiag`` might help on Windows. Press ``Windows+R`` and type ``dxdiag``. In the screen that will appear you can find a button that saves your computer info. Attach that here!

  4. Every Higurashi chapter has a feature that saves a log containing all the tech stuff to fix issues. If your game crashes or looks broken, go into ``HigurashiEp0*_Data`` and upload the file ``output_log.txt`` for us. :)
